name: columnar_output
description: Provide formatted output in columns using Markdown or HTML.
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^2.2.0

dev_dependencies:
  test: ^1.17.12
